title: johnconn 
description: johnconn's personal website 

url: https://github.com/jconn/jconn.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html

social:
  github: jconn 
  email: john.will.connolly@gmail.com

#google_analytics: "UA-58263416-1"

#disqus:
#    shortname: brianmaierjr
